const http = require('node:http');
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const PORT = Number(process.env.PORT || 3000);
const MAX_BYTES = 12 * 1024 * 1024;
const MANUS_API_URL = String(process.env.MANUS_API_URL || '').replace(/\/$/, '');
const MANUS_API_KEY = process.env.MANUS_API_KEY || '';
const GOOGLE_APPS_SCRIPT_URL = process.env.GOOGLE_APPS_SCRIPT_URL || '';
const GOOGLE_APPS_SCRIPT_TOKEN = process.env.GOOGLE_APPS_SCRIPT_TOKEN || '';

const schema = {
  type: 'object', additionalProperties: false,
  properties: {
    invoiceNo:{type:'string'}, companyName:{type:'string'}, taxId:{type:'string'}, invoiceDate:{type:'string'}, salesperson:{type:'string'}, grandTotalInclVat:{type:'number'}, vatStatus:{type:'string', enum:['inclusive','exclusive','unknown']}, vatRate:{type:'number'},
    items:{type:'array', items:{type:'object', additionalProperties:false, properties:{gpuCode:{type:'string'}, tpuCode:{type:'string'}, productName:{type:'string'}, quantity:{type:'number'}, unitPriceInclVat:{type:'number'}, totalPriceInclVat:{type:'number'}}, required:['gpuCode','tpuCode','productName','quantity','unitPriceInclVat','totalPriceInclVat']}}
  }, required:['invoiceNo','companyName','taxId','invoiceDate','salesperson','grandTotalInclVat','vatStatus','vatRate','items']
};

function json(res, status, body) { const data = JSON.stringify(body); res.writeHead(status, {'content-type':'application/json; charset=utf-8', 'cache-control':'no-store'}); res.end(data); }
function readBody(req) { return new Promise((resolve,reject)=>{let size=0, chunks=[];req.on('data',chunk=>{size+=chunk.length;if(size>MAX_BYTES*1.5){reject(new Error('request too large'));req.destroy();return}chunks.push(chunk)});req.on('end',()=>{try{resolve(JSON.parse(Buffer.concat(chunks).toString('utf8')))}catch(e){reject(new Error('invalid JSON'))}});req.on('error',reject)}) }
function assertConfig() { if(!MANUS_API_URL || !MANUS_API_KEY) throw new Error('Manus runtime is not configured'); if(!GOOGLE_APPS_SCRIPT_URL || !GOOGLE_APPS_SCRIPT_TOKEN) throw new Error('Google Apps Script bridge is not configured'); }
function normalize(data) {
  const invoice = data || {}; const warnings=[]; const vatStatus=invoice.vatStatus || 'unknown'; const multiplier=vatStatus==='exclusive'?1.07:1;
  if(vatStatus==='unknown') warnings.push('ไม่พบหลักฐานชัดเจนว่า VAT รวมแล้วหรือไม่ กรุณาตรวจสอบราคา');
  const taxId=String(invoice.taxId||'').replace(/[- ]/g,''); if(taxId && !/^\d{13}$/.test(taxId)) warnings.push('เลขประจำตัวผู้เสียภาษีควรมี 13 หลัก');
  const items=(Array.isArray(invoice.items)?invoice.items:[]).map(item=>{const gpu=String(item.gpuCode||''),tpu=String(item.tpuCode||'');if(gpu&&!/^\d{5,8}$/.test(gpu))warnings.push('GPU Code ต้องมี 5–8 หลัก');if(tpu&&!/^\d{5,8}$/.test(tpu))warnings.push('TPU Code ต้องมี 5–8 หลัก');const q=Number(item.quantity)||0,u=Math.round((Number(item.unitPriceInclVat)||0)*multiplier*100)/100,t=Math.round((Number(item.totalPriceInclVat)||0)*multiplier*100)/100;if(q&&u&&t&&Math.abs(q*u-t)>.05)warnings.push('ยอดรวมรายการไม่ตรงกับ จำนวน × ราคา/หน่วย: '+(item.productName||'รายการ'));return {gpuCode:gpu,tpuCode:tpu,productName:String(item.productName||''),quantity:q,unitPriceInclVat:u,totalPriceInclVat:t}});
  const grand=Math.round((Number(invoice.grandTotalInclVat)||0)*multiplier*100)/100;const sum=items.reduce((n,x)=>n+x.totalPriceInclVat,0);if(grand&&sum&&Math.abs(sum-grand)>.1)warnings.push('ยอดรวมสุทธิไม่ตรงกับผลรวมรายการ');
  return {invoice:{invoiceNo:String(invoice.invoiceNo||''),companyName:String(invoice.companyName||''),taxId,invoiceDate:String(invoice.invoiceDate||''),salesperson:String(invoice.salesperson||''),grandTotalInclVat:grand,vatStatus,imageUrl:String(invoice.imageUrl||'')},items,warnings:[...new Set(warnings)]};
}
async function manus(path, options={}) { const response=await fetch(MANUS_API_URL+path,{...options,headers:{authorization:'Bearer '+MANUS_API_KEY,'content-type':'application/json',...(options.headers||{})}}); const body=await response.json().catch(()=>({})); if(!response.ok||body.error) throw new Error(body.error?.message||body.error||`Manus API ${response.status}`); return body; }
async function storeObject(base64,mimeType,fileName) { const key=`invoice-ocr/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}-${String(fileName||'invoice').replace(/[^a-zA-Z0-9._-]/g,'_')}`;const presign=await manus('/v1/storage/presign/put?path='+encodeURIComponent(key),{method:'GET',headers:{}});const put=await fetch(presign.url,{method:'PUT',headers:{'content-type':mimeType},body:Buffer.from(base64,'base64')});if(!put.ok)throw new Error('Manus storage upload failed');const get=await manus('/v1/storage/presign/get?path='+encodeURIComponent(key),{method:'GET',headers:{}});return {key,downloadUrl:get.url,stableUrl:'/manus-storage/'+key}; }
async function ocr(file) { const stored=await storeObject(file.base64,file.mimeType,file.fileName);const prompt='อ่านข้อความจากใบกำกับภาษี/บิล inventory ภาษาไทยหรืออังกฤษ แล้วคืน JSON ตาม schema เท่านั้น. vatStatus เป็น inclusive เมื่อรวม VAT แล้ว, exclusive เมื่อมีหลักฐานชัดเจนว่าไม่รวม VAT, มิฉะนั้น unknown. ราคาที่ส่งออกต้องเป็น VAT 7% inclusive; ระบบจะคูณ 1.07 เมื่อ vatStatus=exclusive. รหัส GPU/TPU เป็นตัวเลข 5-8 หลัก';const body=await manus('/v1/chat/completions',{method:'POST',body:JSON.stringify({model:process.env.MANUS_OCR_MODEL||'gemini-3-flash-preview',messages:[{role:'system',content:'คุณเป็นระบบ OCR ใบกำกับภาษีที่คืนข้อมูล JSON เท่านั้น'},{role:'user',content:[{type:'text',text:prompt},{type:'image_url',image_url:{url:stored.downloadUrl,detail:'high'}}]}],temperature:0.1,response_format:{type:'json_schema',json_schema:{name:'invoice_ocr',strict:true,schema}}})});const text=body.choices?.[0]?.message?.content;if(!text)throw new Error('Manus OCR ไม่คืนผลลัพธ์');let extracted;try{extracted=JSON.parse(text)}catch(e){throw new Error('Manus OCR คืน JSON ไม่ถูกต้อง')}const normalized=normalize(extracted);return {data:{...normalized,invoice:{...normalized.invoice,imageUrl:''},storage:stored}};}
async function bridge(action,payload){if(!GOOGLE_APPS_SCRIPT_URL||!GOOGLE_APPS_SCRIPT_TOKEN)throw new Error('Google Apps Script bridge is not configured');const r=await fetch(GOOGLE_APPS_SCRIPT_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token:GOOGLE_APPS_SCRIPT_TOKEN,action,payload})});const b=await r.json().catch(()=>({}));if(!r.ok||!b.ok)throw new Error(b.error||`Google bridge ${r.status}`);return b;}
function serveStatic(req,res){const pathname=new URL(req.url,'http://localhost').pathname;const file=pathname==='/'?'index.html':pathname==='/index.html'?'index.html':pathname==='/manus-routes.json'?'manus-routes.json':pathname.startsWith('/public/')?pathname.slice(1):null;if(!file)return false;const filePath=path.resolve(process.cwd(),file);if(!filePath.startsWith(path.resolve(process.cwd())+path.sep)||!fs.existsSync(filePath))return false;const ext=path.extname(filePath);const types={'.html':'text/html; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.ico':'image/x-icon'};res.writeHead(200,{'content-type':types[ext]||'application/octet-stream','cache-control':ext==='.html'?'no-cache':'public, max-age=3600'});fs.createReadStream(filePath).pipe(res);return true;}
async function route(req,res){if(req.method==='GET'&&req.url==='/health')return json(res,200,{ok:true,service:'invoice-ocr-manus'});if(req.method==='GET'&&serveStatic(req,res))return;if(req.method!=='POST'||!['/api/ocr','/api/save'].includes(req.url))return json(res,404,{ok:false,error:'Not found'});try{assertConfig();const body=await readBody(req);if(req.url==='/api/ocr'){if(!body.base64||!body.mimeType)throw new Error('กรุณาเลือกไฟล์บิล');const bytes=Buffer.from(body.base64,'base64');if(bytes.length>MAX_BYTES)throw new Error('ไฟล์ใหญ่เกิน 12 MB');const drive=await bridge('saveImage',{base64:body.base64,mimeType:body.mimeType,fileName:body.fileName});const result=await ocr(body);result.data.invoice.imageUrl=drive.data.url;result.data.invoice.fileId=drive.data.id;return json(res,200,{ok:true,data:result.data,warnings:result.data.warnings})}const saved=await bridge('saveInvoice',body);return json(res,200,saved)}catch(error){return json(res,400,{ok:false,error:error.message||'Request failed'})}}
http.createServer((req,res)=>route(req,res)).listen(PORT,'0.0.0.0',()=>console.log(`invoice-ocr-manus listening on ${PORT}`));
